### ISSUE TITLE
build issue `VcpuExit::FailEntry`

### ISSUE THREAD

**Issue by dirkmueller** [containers/libkrun#101] opened 2022-12-05 13:37 UTC
failed on 

```
 error[E0532]: expected unit struct, unit variant or constant, found tuple variant `VcpuExit::FailEntry`
     --> src/vmm/src/linux/vstate.rs:1169:17
      |
 1169 |                 VcpuExit::FailEntry => {
      |                 ^^^^^^^^^^^^^^^^^^^ help: use the tuple variant pattern syntax instead: `VcpuExit::FailEntry(/* fields */)`
      |
     ::: /home/abuild/rpmbuild/BUILD/libkrun-1.4.6/vendor/kvm-ioctls/src/ioctls/vcpu.rs:59:5
      |
 59 |     FailEntry(
      |     --------- `VcpuExit::FailEntry` defined here

```

it appears this patch resolves the issue:

```patch
--- a/src/vmm/src/linux/vstate.rs
+++ b/src/vmm/src/linux/vstate.rs
@@ -1166,7 +1166,7 @@ impl Vcpu {
                 }
                 // Documentation specifies that below kvm exits are considered
                 // errors.
-                VcpuExit::FailEntry => {
+                VcpuExit::FailEntry(..) => {
                     error!("Received KVM_EXIT_FAIL_ENTRY signal");
                     Err(Error::VcpuUnhandledKvmExit)
                 }

```

**Comment by slp** [comment] 2023-01-19 07:12
This was caused by API breaking changes in `kvm-ioctls` / `kvm-bindings`. Should be fixed in v1.4.10

**Closed by slp** 2023-01-19 07:12 UTC
